#!/usr/bin/env bash
# Multi-purpose pre-commit hook
# Place this at .git/hooks/pre-commit and chmod +x
#
# Sections:
#   1. State-machine JSON validation
#      Source:  harness-rules.md 铁律 #11
#      Trigger: MVP-internal-demo-prep commit b44b79d shipped progress.json with a missing
#               closing `}` to main, broke downstream parsers for hours.
#      Guard:   parse JSON pre-commit, reject on failure.
#
#   2. Material Symbols subset coverage (BL-027-F004 · framework v0.9.7)
#      Source:  docs/specs/BL-027-asset-followup-icon-hotfix-spec.md §F004
#      Trigger: BL-026 F002 added filter_alt + arrow_drop_down callsites in
#               AssetsClient.tsx but the regenerate script wasn't run, shipping
#               literal "FILTER_ALT" / "ARROW_DROP_DOWN" to prod.
#      Guard:   when staged files touch icon usage, run the regenerate script
#               and verify the resulting woff2 matches what's staged. Reject
#               commit if the script produces a different woff2 that wasn't
#               staged alongside the icon change.

# Note: NOT using `set -e` — we want to collect all failures and report them
# together, then exit 1 at the end if any failed. With set -e, an early grep
# returning 1 (no match) would abort the hook prematurely.

failed=0

# ---------------------------------------------------------------------------
# Section 1: State-machine JSON validation
# ---------------------------------------------------------------------------
STATE_FILES=(
  "progress.json"
  "features.json"
  "backlog.json"
)

for file in "${STATE_FILES[@]}"; do
  # 仅检查本次 commit 中实际改动的状态机文件（不阻塞无关 commit）
  if git diff --cached --name-only | grep -q "^${file}$"; then
    if ! python3 -c "import json; json.load(open('${file}'))" 2>/dev/null; then
      echo "❌ pre-commit: ${file} JSON parse failed."
      python3 -c "import json; json.load(open('${file}'))" 2>&1 | head -5
      failed=1
    else
      echo "✓ pre-commit: ${file} JSON valid"
    fi
  fi
done

# ---------------------------------------------------------------------------
# Section 2: Material Symbols subset coverage (BL-027-F004)
# ---------------------------------------------------------------------------
WOFF2_PATH="src/app/fonts/material-symbols-outlined.woff2"
REGEN_SCRIPT="scripts/regenerate-material-symbols-subset.sh"
MANIFEST_PATH="scripts/material-symbols-icons-manifest.txt"

icon_files_staged=false
while IFS= read -r staged_file; do
  # Restrict to staged source files (.ts / .tsx under src/) and the
  # explicit icon manifest. Anything else can't introduce a new icon
  # callsite that the regen script would care about.
  case "$staged_file" in
    src/*.ts|src/*.tsx|src/*/*.ts|src/*/*.tsx|src/*/*/*.ts|src/*/*/*.tsx|src/*/*/*/*.ts|src/*/*/*/*.tsx|src/*/*/*/*/*.ts|src/*/*/*/*/*.tsx|src/*/*/*/*/*/*.ts|src/*/*/*/*/*/*.tsx|"$MANIFEST_PATH")
      # Cheap pre-check: does the staged file even mention the
      # material-symbols class or look like a manifest line of
      # icon names? If not, skip the expensive script run.
      if [ -f "$staged_file" ] && grep -qE 'material-symbols-outlined|^[a-z_][a-z_0-9]*$' "$staged_file" 2>/dev/null; then
        icon_files_staged=true
        break
      fi
      ;;
  esac
done < <(git diff --cached --name-only --diff-filter=ACM)

if $icon_files_staged; then
  echo "→ pre-commit: detected Material Symbols icon callsite changes — verifying woff2 ..."
  if [ ! -f "$REGEN_SCRIPT" ]; then
    echo "❌ pre-commit: regenerate script not found at $REGEN_SCRIPT"
    failed=1
  elif [ ! -f "$WOFF2_PATH" ]; then
    echo "❌ pre-commit: woff2 not found at $WOFF2_PATH"
    failed=1
  else
    before_hash=$(sha256sum "$WOFF2_PATH" | awk '{print $1}')
    if ! bash "$REGEN_SCRIPT" > /dev/null 2>&1; then
      echo "❌ pre-commit: $REGEN_SCRIPT failed (network? quota? typo in manifest?). Re-run manually to see the error."
      failed=1
    else
      after_hash=$(sha256sum "$WOFF2_PATH" | awk '{print $1}')
      if [ "$before_hash" != "$after_hash" ]; then
        if git diff --cached --name-only | grep -qx "$WOFF2_PATH"; then
          echo "✓ pre-commit: woff2 staged + matches script output"
        else
          echo "❌ pre-commit: woff2 was regenerated by the script but is NOT staged."
          echo "   Run:"
          echo "     git add $WOFF2_PATH"
          echo "   then redo this commit. (To bypass: git commit --no-verify — not recommended.)"
          failed=1
        fi
      else
        echo "✓ pre-commit: woff2 already up-to-date"
      fi
    fi
  fi
fi

# ---------------------------------------------------------------------------
# Final verdict
# ---------------------------------------------------------------------------
if [ "$failed" -ne 0 ]; then
  echo ""
  echo "Commit rejected. Fix the issues above and re-commit."
  echo "Bypass (not recommended): git commit --no-verify"
  exit 1
fi

exit 0
