"""Schemas for ``GET /api/dashboard`` (F006 Home / Dashboard)."""

from __future__ import annotations

from pydantic import BaseModel, Field


class LastRebalance(BaseModel):
    """Most recent rebalance summary surfaced on the home card."""

    date: str = Field(description="ISO-8601 date the master portfolio was rebalanced.")
    fill_count: int = Field(ge=0, description="Number of fills generated by the rebalance.")
    slippage_bps: float = Field(description="Realised slippage vs the target prices, in bps.")


class RecentReport(BaseModel):
    """Compact link surfaced in the recent-reports rail."""

    id: str
    title: str
    date: str = Field(description="ISO-8601 date the report was filed.")
    status: str = Field(description="Free-form status string, e.g. 'PASS' / 'PARTIAL' / 'FAIL'.")
    path: str = Field(description="Repo-relative path; deep-linked via /api/docs/{path}.")


class ActionItem(BaseModel):
    """Single attention-required entry in the home action panel."""

    id: str
    severity: str = Field(description="One of 'info' / 'warning' / 'critical' (UI convention).")
    message: str


class DashboardResponse(BaseModel):
    """Composite response for the home/dashboard page."""

    nav: float = Field(description="Latest known net asset value in account currency.")
    master_drawdown: float = Field(
        description="Current drawdown vs equity peak, as a ratio (-0.05 = -5%)."
    )
    kill_switch_threshold: float = Field(
        description="Drawdown threshold (ratio) that arms the kill switch."
    )
    days_to_next_rebalance: int = Field(ge=0)
    last_rebalance: LastRebalance | None = None
    recent_reports: list[RecentReport]
    action_items: list[ActionItem]
